"""add error_message to extraction_jobs

Revision ID: b009557efab0
Revises: be62e0f73ed9
Create Date: 2026-09-16 16:35:08.762256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b009557efab0'
down_revision: Union[str, None] = 'be62e0f73ed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_jobs', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extraction_jobs', 'error_message')
    # ### end Alembic commands ###
